name: Build and push to quay.io
on:
  push:
    branches: [ main ]

env:
  REGISTRY_USER: netobserv+github_ci
  REGISTRY: quay.io/netobserv
  IMAGE: flowlogs-pipeline
  ORG: netobserv
  VERSION: main

jobs:
  push-image:
    name: push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19']
    steps:
      - name: install make
        run: sudo apt-get install make
      - name: set up go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: checkout
        uses: actions/checkout@v3
      - name: docker login to quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
          registry: quay.io
      - name: build and push manifest with images
        run: IMAGE_ORG=${{ env.ORG }} OCI_BIN=docker VERSION=${{ env.VERSION }} make ci
